# Generated by Django 3.2.11 on 2022-01-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(default='0', max_length=10)),
                ('room_no', models.CharField(max_length=6)),
                ('name', models.CharField(default='0', max_length=101)),
                ('is_alloted', models.BooleanField(default=False)),
                ('block', models.CharField(max_length=1)),
            ],
        ),
    ]
