# Generated by Django 3.2.11 on 2022-01-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
