# Generated by Django 3.2.11 on 2022-01-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220120_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_alloted',
            field=models.BooleanField(default=False),
        ),
    ]
