# Generated by Django 3.2.11 on 2022-01-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_alloted'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='room_no',
            field=models.CharField(default='0', max_length=6),
        ),
    ]
