# Generated by Django 3.2.11 on 2022-02-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='room_no',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
